# -*- coding: utf-8 -*-
"""Per-user Windows installer for the ``gsi://personal`` protocol.

Security / deployment properties
--------------------------------
* HKCU only; no administrator or machine-wide registry write is required.
* Operational data is never copied locally by the installer.
* ``personal_config.json`` stores only the shared-folder path and employee code.
* The per-user AES key is stored outside the shared folder under LOCALAPPDATA.
* Prefer ``--user-key-file`` over putting a key on the command line.
* A tiny local launcher pins the current GSI package root, so the protocol still
  works when GSI is run from a source folder rather than installed with pip.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


def _local_dir() -> Path:
    base = os.environ.get("LOCALAPPDATA") or os.path.expanduser("~")
    return Path(base) / "GSI"


def _restrict_file_windows(path: Path) -> None:
    if not sys.platform.startswith("win"):
        return
    user = os.environ.get("USERNAME", "")
    if not user:
        return
    try:
        subprocess.run(
            ["icacls", str(path), "/inheritance:r", "/grant:r", f"{user}:(R,W)"],
            check=False, capture_output=True, text=True,
        )
    except Exception:
        pass


def _read_key_from_args(ns: argparse.Namespace) -> str:
    """Return a user key without requiring it to appear in shell history."""
    if ns.user_key_file:
        p = Path(ns.user_key_file).expanduser()
        if not p.is_file():
            raise SystemExit(f"فایل User Key پیدا نشد: {p}")
        return p.read_text(encoding="utf-8").strip()
    # Backward compatibility only. Kept so older deployment notes do not break,
    # but the help text explicitly discourages it because process lists/shell
    # history may expose command-line secrets.
    return (ns.user_key or "").strip()


def _write_launcher(local: Path, package_root: Path) -> Path:
    """Write a local helper that imports GSI from the exact deployed folder."""
    launcher = local / "gsi_personal_launcher.py"
    source = f'''# Auto-generated by GSI V27.1 installer.\nimport sys\nfrom pathlib import Path\nROOT = Path(r"{str(package_root)}")\nif str(ROOT) not in sys.path:\n    sys.path.insert(0, str(ROOT))\nfrom gsi.personalization.launcher import render_and_open\nrender_and_open()\n'''
    launcher.write_text(source, encoding="utf-8")
    _restrict_file_windows(launcher)
    return launcher


def main(argv=None) -> int:
    if not sys.platform.startswith("win"):
        raise SystemExit("این Installer فقط روی Windows اجرا می‌شود.")
    import winreg

    ap = argparse.ArgumentParser()
    ap.add_argument("--employee", required=True)
    ap.add_argument(
        "--root", required=True,
        help=r"UNC/Shared Folder root, e.g. \\server\share\GSI\Users",
    )
    ap.add_argument(
        "--user-key-file", default="",
        help="مسیر فایل User Key؛ روش پیشنهادی چون Key در command line ظاهر نمی‌شود.",
    )
    ap.add_argument(
        "--user-key", default="",
        help="User Key Base64 (سازگاری قدیمی؛ برای استقرار Production توصیه نمی‌شود).",
    )
    ns = ap.parse_args(argv)

    from gsi.core.text import clean_employee_code
    emp = clean_employee_code(ns.employee)
    if not emp:
        raise SystemExit("کد پرسنلی نامعتبر است.")

    root = str(ns.root).strip()
    if not root:
        raise SystemExit("مسیر Shared Folder خالی است.")

    local = _local_dir()
    local.mkdir(parents=True, exist_ok=True)

    identity = local / "identity.json"
    identity.write_text(
        json.dumps({"employee_code": emp}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    _restrict_file_windows(identity)

    key_path = local / "profile.key"
    config = local / "personal_config.json"
    # No operational payload and no key material is stored in this JSON.
    config.write_text(
        json.dumps(
            {
                "profile_root": root,
                "employee_code": emp,
                "user_key_file": str(key_path),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    _restrict_file_windows(config)

    key_text = _read_key_from_args(ns)
    if key_text:
        key_path.write_text(key_text, encoding="utf-8")
        _restrict_file_windows(key_path)

    package_root = Path(__file__).resolve().parents[2]
    launcher = _write_launcher(local, package_root)

    base = r"Software\Classes\gsi"
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, base) as k:
        winreg.SetValueEx(k, "", 0, winreg.REG_SZ, "URL:GSI Personal Workspace")
        winreg.SetValueEx(k, "URL Protocol", 0, winreg.REG_SZ, "")

    # Pass %1 for a standards-compliant URL protocol handler. The launcher does
    # not use the URI contents for identity/data lookup; identity stays local.
    command = f'"{sys.executable}" "{launcher}" "%1"'
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, base + r"\shell\open\command") as k:
        winreg.SetValueEx(k, "", 0, winreg.REG_SZ, command)

    print(f"Identity: {identity}")
    print(f"Config: {config}")
    print(f"Launcher: {launcher}")
    if key_path.exists():
        print(f"User key: {key_path}")
    else:
        print("User key: نصب نشده — قبل از بازکردن داده، profile.key را از کانال امن قرار دهید.")
    print("Protocol: gsi://personal")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
